edac: introduce edac feature into lkvs
intel/lkvs pull request #229
Opened 2024-05-23 07:34 UTC by laifryiee

Intel i10nm EDAC driver supports the Intel 10nm series server integrated memory controller. Introduce this feature into lkvs test suite and add 2 test cases.

2024-05-24 06:06 UTC, ysun requested changes

2024-05-24 06:06 UTC, ysun commented on BM/edac/README.md
> +EDAC (Error Detection and Correction) framework provids support for detecting and correcting memory errors on systems with ECC (Error-Correcting Code) memory or other error detection mechanism.
typo: provids.

2024-05-24 06:06 UTC, ysun commented on BM/edac/README.md
> +EDAC (Error Detection and Correction) framework provids support for detecting and correcting memory errors on systems with ECC (Error-Correcting Code) memory or other error detection mechanism.
Others in the patch look good to me.

2024-05-24 06:16 UTC, laifryiee commented
Thanks for review. Commit is force updated.

2024-05-24 10:04 UTC, ysun commented
Hi LaiYi,

One coding style check issue need fix:

>>>> Taints found in file: BM/edac/intel_edac.sh
>>>> Hints:
    BM/edac/intel_edac.sh:3[8](https://github.com/intel/lkvs/actions/runs/9219553211/job/25370823112?pr=229#step:4:9) - Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181
Error: Process completed with exit code 1.>>>> Taints found in file: BM/edac/intel_edac.sh
>>>> Hints:
    BM/edac/intel_edac.sh:3[8](https://github.com/intel/lkvs/actions/runs/9219553211/job/25370823112?pr=229#step:4:9) - Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181
Error: Process completed with exit code 1.>>>> Taints found in file: BM/edac/intel_edac.sh
>>>> Hints:
    BM/edac/intel_edac.sh:3[8](https://github.com/intel/lkvs/actions/runs/9219553211/job/25370823112?pr=229#step:4:9) - Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181
Error: Process completed with exit code 1.

2024-05-27 02:59 UTC, laifryiee commented
> Hi LaiYi,
> 
> One coding style check issue need fix:
> 
> > > > > Taints found in file: BM/edac/intel_edac.sh
> > > > > Hints:
> > > > > BM/edac/intel_edac.sh:3[8](https://github.com/intel/lkvs/actions/runs/9219553211/job/25370823112?pr=229#step:4:9) - Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181
> > > > > Error: Process completed with exit code 1.>>>> Taints found in file: BM/edac/intel_edac.sh
> > > > > Hints:
> > > > > BM/edac/intel_edac.sh:3[8](https://github.com/intel/lkvs/actions/runs/9219553211/job/25370823112?pr=229#step:4:9) - Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181
> > > > > Error: Process completed with exit code 1.>>>> Taints found in file: BM/edac/intel_edac.sh
> > > > > Hints:
> > > > > BM/edac/intel_edac.sh:3[8](https://github.com/intel/lkvs/actions/runs/9219553211/job/25370823112?pr=229#step:4:9) - Check exit code directly with e.g. 'if ! mycmd;', not indirectly with $?., refer to https://github.com/koalaman/shellcheck/wiki/SC2181
> > > > > Error: Process completed with exit code 1.

Modified accoring to reference coding style.

2024-05-27 03:00 UTC, closed without merging